<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-SK32KMA" name="Test" tests="6" failures="2" timestamp="21 Jun 2022 11:17:32 GMT" time="0.132" errors="0">
  <testcase name="tc1" time="0.018" classname="org.tng.TestClass"/>
  <testcase name="tc1" time="0.017" classname="org.tng.TestClass2"/>
  <testcase name="tc2" time="0.015" classname="org.tng.TestClass">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at org.tng.TestClass.tc2(TestClass.java:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc3" time="0.0" classname="org.tng.TestClass">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at org.tng.TestClass.tc3(TestClass.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
  <testcase name="tc2" time="0.048" classname="org.tng.TestClass2"/>
  <testcase name="tc3" time="0.0" classname="org.tng.TestClass2"/>
</testsuite> <!-- Test -->
